export const cuisineList = [
  "Samosa",
  "Aloo Paratha",
  "Paneer Paratha",
  "Burgers",
  "Coffee",
  "Fried Maggie",
  "Simple Maggie",
  "French Fries",
  "Paneer Roll",
  "Veg Kabab",
  "Boiled Egg",
  "Single Egg Omelette",
  "Double Egg Omelette",
  "Half Fry",
  "Noodles",
  "Sandwich",
  "Pasta",
  "Pizza",
  "Sedha Namak",
  "Dahibara",
  "Chole Bhature",
  "Tropicana",
  "Coca-Cola",
  "Sprite",
  "Fanta",
  "Dosa",
];